# Generated by Django 2.2.8 on 2020-02-19 08:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200129_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='bike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Bike'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='customer',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer'),
            preserve_default=False,
        ),
    ]
